name: ▶ Build the Directory!

on:
    workflow_dispatch:

permissions: write-all

concurrency:
    group: "fetch-data"
    cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:

  fetch-devs:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive
          fetch-depth: 0
      - id: fetch-data
        name: Fetch Data
        uses: jroehl/gsheet.action@v2.0.0
        with: 
          spreadsheetId: 1baXLkmhphVF2vPQGA0tuFmQgdWkasd0PPqUXqasAc0U
          commands: |
            [
              { "command": "getData", "args": { "range": "'Form Responses 1'!B1:E99", "hasHeaderRow": true }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: Save Data
        id: save-data
        env: 
          RESULTS: ${{ steps.fetch-data.outputs.results }}
        run: |
          data_file="data/directory/developers.json"
          mkdir -p data
          test -f $data_file || touch $data_file
          data_node=$(echo $RESULTS | jq)
          data_node_result=$(echo $data_node | jq -r '.results[0].result.rawData' )
          if [ $data_node_result = $(cat $data_file) ]
          then
            exit 1
          fi
          echo $data_node_result > $data_file
      - name: Commit Change
        id: commit-change
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "no-reply@github.com"
          git tag updated-developer-directory
          git add data/directory/developers.json
          git commit -m "Update Developer Directory"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  fetch-projs:
    needs: fetch-devs
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive
          fetch-depth: 0
      - id: fetch-data
        name: Fetch Data
        uses: jroehl/gsheet.action@v2.0.0
        with: 
          spreadsheetId: 1ohwGWivfroYJHw-vItRxOptz3VgIn_L500gP4bV6Mhk
          commands: |
            [
              { "command": "getData", "args": { "range": "'Form Responses 1'!B1:F99", "hasHeaderRow": true }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: Save Data
        id: save-data
        env: 
          RESULTS: ${{ steps.fetch-data.outputs.results }}
        run: |
          data_file="data/directory/projects.json"
          mkdir -p data
          test -f $data_file || touch $data_file
          data_node=$(echo $RESULTS | jq)
          data_node_result=$(echo $data_node | jq -r '.results[0].result.rawData' )
          if [ $data_node_result = $(cat $data_file) ]
          then
            exit 1
          fi
          echo $data_node_result > $data_file
      - name: Commit Change
        id: commit-change
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "no-reply@github.com"
          git tag updated-projects-showcase
          git add data/directory/projects.json
          git commit -m "Update Projects Showcase"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build:
    uses: ./.github/workflows/hugo-build.yaml
    needs: [fetch-devs, fetch-projs]
    if: |
      always()
      && contains(needs.*.result, 'success')

