name: ▶ Build the Event List!

on:
  workflow_dispatch:

permissions: write-all

concurrency:
  group: "fetch-data"
  cancel-in-progress: false

defaults:
  run: 
    shell: bash

jobs:

  fetch-events:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive
          fetch-depth: 0
      - id: fetch-data
        name: Fetch Data
        uses: jroehl/gsheet.action@v2.0.0
        with:
          spreadsheetId: 1pwm3XCmQBIXZ40VByoLZ7CPBpIaNCeqcE0wKGrrmd5A
          commands: |
            [
              { "command": "getData", "args": { "range": "'Form Responses 1'!B1:E99", "hasHeaderRow": true }}
            ]
          env:
            GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
            GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: Save Data
        id: save-data
        env: 
          RESULTS: ${{ steps.fetch-data.outputs.results }}
        run: |
          git pull
          data_file="data/events.json"
          mkdir -p data
          test -f $data_file || touch $data_file
          data_node=$(echo $RESULTS | jq)
          data_node_result=$(echo $data_node | jq -r '.results[0].result.rawData' )
          if [ "$data_node_result" = "$(cat $data_file)" ]
          then
            exit 1
          fi
          echo $data_node_result > $data_file
      - name: Commit Change
        id: commit-change
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "
          git tag updated-event-list
          git add data/events.json
          git commit -m "Updated event list"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  build:
    uses: ./.github/workflows/hugo-build.yaml
    needs: fetch-events
