name: ▶ Build the Directory!

on:
    workflow_dispatch:

permissions: write-all

defaults:
  run:
    shell: bash

jobs:

  fetch-data:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive
          fetch-depth: 0
      - id: fetch-devs
        name: Fetch Devs
        uses: jroehl/gsheet.action@v2.0.0
        with: 
          spreadsheetId: 1baXLkmhphVF2vPQGA0tuFmQgdWkasd0PPqUXqasAc0U
          commands: |
            [
              { "command": "getData", "args": { "range": "'Form Responses 1'!B1:E99", "hasHeaderRow": true }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: Save Devs
        id: save-devs
        env: 
          RESULTS: ${{ steps.fetch-data.outputs.results }}
        run: |
          data_file="data/directory/developers.json"
          mkdir -p data
          test -f $data_file || touch $data_file
          data_node=$(echo $RESULTS | jq)
          data_node_result=$(echo $data_node | jq -r '.results[0].result.rawData' )
          had_devs=false
          echo $data_node_result
          echo $(cat $data_file)
          if [ "$data_node_result" != "$(cat $data_file)" ]
          then
            echo $data_node_result > $data_file
            had_devs=true
          fi
          echo "had_devs=$had_devs" >> "$GITHUB_ENV"
      - id: fetch-projects
        name: Fetch Projects
        uses: jroehl/gsheet.action@v2.0.0
        with: 
          spreadsheetId: 1ohwGWivfroYJHw-vItRxOptz3VgIn_L500gP4bV6Mhk
          commands: |
            [
              { "command": "getData", "args": { "range": "'Form Responses 1'!B1:F99", "hasHeaderRow": true }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: Save Projects
        id: save-projects
        env: 
          RESULTS: ${{ steps.fetch-data.outputs.results }}
        run: |
          data_file="data/directory/projects.json"
          mkdir -p data
          test -f $data_file || touch $data_file
          data_node=$(echo $RESULTS | jq)
          data_node_result=$(echo $data_node | jq -r '.results[0].result.rawData' )
          had_projs=false
          echo $data_node_result
          echo $(cat $data_file)
          if [ "$data_node_result" != "$(cat $data_file)" ]
          then
            echo $data_node_result > $data_file
            had_projs=true
          fi
          echo "had_projs=$had_projs" >> "$GITHUB_ENV"
      - name: Commit Change
        id: commit-change
        run: |
          if [ $had_devs == true ] || [ $had_projs == true ]
          then
            git config --global user.name "GitHub Actions"
            git config --global user.email "no-reply@github.com"
            if [ $had_devs == true ]
            then
              git tag updated-developer-directory
              git add data/directory/developers.json
            fi
            if [ $had_projs == true ]
            then
              git tag updated-projects-showcase
              git add data/directory/projects.json
            fi
            git commit -m "Update Directory + Showcase"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
            git push --follow-tags
            exit 0
          fi
          exit 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    uses: ./.github/workflows/hugo-build.yaml
    needs: fetch-data
