name: 🖼️ Generate a New Screenshot of a RoundUp

on:
  workflow_call:
    inputs:
      issue_no:
        required: true
        type: string
      issue_id:
        required: true
        type: string
      base_url:
        required: true
        type: string

permissions: write-all

concurrency:
    group: "pages"
    cancel-in-progress: false

defaults:
    run:
      shell: bash

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps: 
        -   name: Checkout
            uses: actions/checkout@v4
            with: 
                submodules: recursive
                fetch-depth: 0
        -   name: Screenshot
            id: screenshot
            uses: swinton/screenshot-website@v1.x
            with:
                source: "${{ inputs.base_url }}/issue-${{ inputs.issue_no }}/"
                destination: "issue-${{ inputs.issue_no }}.png"
        -   name: Commit image
            run: |
                mkdir -p screenshots
                echo "${{ steps.screenshot.outputs.path }} screenshots/issue-${{inputs.issue_no }}.png"
                mv -f ${{ steps.screenshot.outputs.path }} screenshots/issue-${{inputs.issue_no }}.png
                git config --global user.name "GitHub Actions"
                git config --global user.email "no-reply@github.com"
                git tag generated-screenshot-${{ inputs.issue_no }}
                git add screenshots/issue-${{ inputs.issue_no }}.png
                git commit -m "Update issue image ${{ inputs.issue_no }}"
                git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
                git push --follow-tags 
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
  