name: 🖼️ Generate a New Screenshot of a RoundUp

on:
  workflow_call:
    inputs:
      issue_no:
        required: true
        type: string
      issue_id:
        required: true
        type: string
      base_url:
        required: true
        type: string

permissions: write-all

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Screenshot
      id: screenshot
      uses: swinton/screenshot-website@v1.x
      with:
        source: "${{ inputs.base_url }}/issue-${{ inputs.issue_no }}/"
        destination: "issue-${{ inputs.issue_no }}.png"
    - name: Commit image
      run: "git pull\nmkdir -p screenshots\nmv -f ${{ inputs.outputs.path }} screenshots/issue-${{inputs.issue_no }}.png\ngit config --global user.name \"GitHub Actions\"\ngit config --global user.email \"no-reply@github.com\"\ngit tag generated-screenshot-${{ inputs.issue_no }}\ngit add screenshots/issue-${{ inputs.issue_no }}.png\ngit commit -m \"Update issue image ${{ inputs.issue_no }}\"\ngit remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}\ngit push --follow-tags \n"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


