name: ▶ EMAIL TEST
run-name: EMAIL TEST by @${{ github.actor }}

on:
    workflow_dispatch:

permissions: write-all

defaults:
    run:
        shell: bash

jobs:
  mailchimp:
    runs-on: ubuntu-latest
    steps:
      - name: Create Mailchimp Campaign
        run: |
          id=$(curl -X POST \
          "https://${{ env.MAILCHIMP_DC }}.api.mailchimp.com/3.0/campaigns" \
          --user "admin@stlgame.dev:${{ env.MAILCHIMP_API_KEY }}" \
          --data-raw '{
            "type": "regular",
            "recipients": {
              "list_id": "c120d5d29b"
            },
            "settings": {
              "subject_line": "St Louis Game Developer RoundUp Issue № ${{ env.ISSUE_NO }}",
              "preview_text": "Monthly Game Development News from STLGameDev!",
              "title": "RoundUp № ${{ env.ISSUE_NO }}",
              "from_name": "STLGameDev",
              "reply_to": "news@stlgame.dev",
              "use_conversation": false,
              "to_name": "*|FNAME|*",
              "auto_footer": true,
              "inline_css": true
            },
            "content_type": "multichannel"
          }' | jq -r '.id')
          echo "campaign_id=$id" >> $GITHUB_ENV
        env:
          MAILCHIMP_DC: ${{ secrets.MAILCHIMP_DC }}
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          BASE_URL: https://roundup.stlgame.dev
          ISSUE_NO: 19
      -   name: Checkout
          uses: actions/checkout@v4
          with:
            sparse-checkout: "email-template.html"
      -   name: get content
          id: get-content
          run: |
              url="https://roundup.stlgame.dev/issue-${{ env.ISSUE_NO }}/"
              
              ru_content=$(curl -s $url | awk '/<div id=issue>/,/<\/div>/' )

              if [ -z "$ru_content" ]; then
                ru_content=$(curl -s $url | awk '/<div id="issue">/,/<\/div>/' )
                if [ -z "$ru_content" ]; then
                  echo "Error: Failed to extract content from the URL $url"
                  exit 1
                fi
              fi
              
              email_content=$(cat ${{ github.workspace }}/email-template.html)

              issue_no=${{ env.ISSUE_NO }}

              # escaped_content=$(echo "$ru_content" | sed 's~"~\\"~g' | sed "s~'~\\'~g")
              # email_content=$(echo "$email_content" | sed 's~"~\\"~g' | sed "s~'~\\'~g")

              email_content=$(echo "$email_content" | sed "s~\*\|ISSUE_NO\|\*~$issue_no~g")
              email_content=$(echo "$email_content" | sed "s~\*\|CONTENT\|\*~$escaped_content~g")

              # email_content=$(echo "$email_content" | sed 's~\\\\"~"~g' | sed "s~\\'~'~g")

              email_content=$(echo "$email_content" | tr -d '\n' | tr -d '\r')

              email_content=$(jq -n --arg html "$email_content" '{html: $html}')

              email_content=$(echo "$email_content" | jq -Rs @json)

              echo $email_content

              echo "content=$email_content" >> $GITHUB_ENV

          env:
            MAILCHIMP_DC: ${{ secrets.MAILCHIMP_DC }}
            MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
            BASE_URL: https://roundup.stlgame.dev
            ISSUE_NO: 19
      -   name: update campaign
          run: |
                id=${{ env.campaign_id }}

                data=${{ env.content }}

                echo $data;

                curl -X PUT \
                "https://${{ env.MAILCHIMP_DC }}.api.mailchimp.com/3.0/campaigns/$id/content" \
                --user "admin@stlgame.dev:${{ env.MAILCHIMP_API_KEY }}" \
                --header "Content-Type: application/json" \
                --data-raw "$data"
          env:
            MAILCHIMP_DC: ${{ secrets.MAILCHIMP_DC }}
            MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
            BASE_URL: https://roundup.stlgame.dev
            ISSUE_NO: 19
      -   name: test email
          run: |
            id=${{ env.campaign_id }}

            curl -X POST \
                "https://${{ env.MAILCHIMP_DC }}.api.mailchimp.com/3.0/campaigns/$id/actions/test" \
                --user "admin@stlgame.dev:${{ env.MAILCHIMP_API_KEY }}" \
                -d '{"test_emails":["tim@axolstudio.com"],"send_type":"html"}'
          env:
            MAILCHIMP_DC: ${{ secrets.MAILCHIMP_DC }}
            MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}