name: ▶ EMAIL TEST
run-name: EMAIL TEST by @${{ github.actor }}

on:
    workflow_dispatch:

permissions: write-all

defaults:
    run:
        shell: bash

jobs:
  mailchimp:
    runs-on: ubuntu-latest
    steps:
      - name: Create Mailchimp Campaign
        run: |
          id=$(curl -X POST \
          "https://${{ env.MAILCHIMP_DC }}.api.mailchimp.com/3.0/campaigns" \
          --user "admin@stlgame.dev:${{ env.MAILCHIMP_API_KEY }}" \
          --data-raw '{
            "type": "regular",
            "recipients": {
              "list_id": "c120d5d29b"
            },
            "settings": {
              "subject_line": "St Louis Game Developer RoundUp Issue № ${{ env.ISSUE_NO }}",
              "preview_text": "Monthly Game Development News from STLGameDev!",
              "title": "RoundUp № ${{ env.ISSUE_NO }}",
              "from_name": "STLGameDev",
              "reply_to": "news@stlgame.dev",
              "use_conversation": false,
              "to_name": "*|FNAME|*",
              "auto_footer": true,
              "inline_css": true,
              "template_id": 10138330
            },
            "content_type": "template"
          }' | jq -r '.id')
          echo "campaign_id=$id" >> $GITHUB_ENV
        env:
          MAILCHIMP_DC: ${{ secrets.MAILCHIMP_DC }}
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          BASE_URL: https://roundup.stlgame.dev
          ISSUE_NO: 19
      -   name: Checkout
          uses: actions/checkout@v4
          with:
            sparse-checkout: "email-template.html"
      -   name: get content
          id: get-content
          run: |
              url="https://roundup.stlgame.dev/issue-${{ env.ISSUE_NO }}/"
              
              ru_content=$(curl -s $url | awk '/<div id=issue>/,/<\/div>/' )

              if [ -z "$ru_content" ]; then
                ru_content=$(curl -s $url | awk '/<div id="issue">/,/<\/div>/' )
                if [ -z "$ru_content" ]; then
                  echo "Error: Failed to extract content from the URL $url"
                  exit 1
                fi
              fi
              
              email_content=$(cat ${{ github.workspace }}/email-template.html)

              search="*|ISSUE|*"
              replace=${{ env.ISSUE_NO }}
              email_content=$(echo $email_content | sed "s@$search@$replace@g")

              search="*|CONTENT|*"
              replace=$ru_content
              email_content=$(echo $email_content | sed "s@$search@$replace@g")

              echo "content=$email_content" >> $GITHUB_ENV
          env:
            MAILCHIMP_DC: ${{ secrets.MAILCHIMP_DC }}
            MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
            BASE_URL: https://roundup.stlgame.dev
            ISSUE_NO: 19
      -   name: update campaign
          run: |
                id=${{ env.campaign_id }}

                curl -X PUT \
                https://${{ env.MAILCHIMP_DC }}.api.mailchimp.com/3.0/campaigns/$id/content \
                --user "anystring:${{ env.MAILCHIMP_API_KEY }}" \
                -H "Content-Type: application/json" \
                --data-raw '{"html": "${{ env.content }}"}'
          env:
            MAILCHIMP_DC: ${{ secrets.MAILCHIMP_DC }}
            MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
            BASE_URL: https://roundup.stlgame.dev
            ISSUE_NO: 19