name: ▶ EMAIL TEST
run-name: EMAIL TEST by @${{ github.actor }}

on:
    workflow_dispatch:

permissions: write-all

defaults:
    run:
        shell: bash

jobs:
  mailchimp:
    runs-on: ubuntu-latest
    steps:
      - name: Create Mailchimp Campaign
        run: |
          id=$(curl -X POST \
          "https://${{ env.MAILCHIMP_DC }}.api.mailchimp.com/3.0/campaigns" \
          --user "admin@stlgame.dev:${{ env.MAILCHIMP_API_KEY }}" \
          --data-raw '{
            "type": "regular",
            "recipients": {
                "list_id": "c120d5d29b"
            },
            "settings": {
                "subject_line": "St Louis Game Developer RoundUp Issue № ${{ env.ISSUE_NO }}",
                "preview_text": "Monthly Game Development News from STLGameDev!",
                "title": "RoundUp № ${{ env.ISSUE_NO }}",
                "from_name": "STLGameDev",
                "reply_to": "news@stlgame.dev",
                "use_conversation": false,
                "to_name": "*|FNAME|*",
                "auto_footer": true,
                "inline_css": true
            },
            "content_type": "template"
          }' | jq -r '.id')
          echo "campaign_id=$id" >> $GITHUB_ENV
        env:
          MAILCHIMP_DC: ${{ secrets.MAILCHIMP_DC }}
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          BASE_URL: https://roundup.stlgame.dev
          ISSUE_NO: 19

      -   name: get issue content
          id: issue-content
          run: |
              url="${{ env.BASE_URL }}/issue-${{ env.ISSUE_NO }}/email.html"
              
              ru_content=$(curl -s $url)

              
              ru_content=$(echo $ru_content | sed 's/\\/\\\\/g')
              ru_content=$(echo $ru_content | sed 's/"/\\"/g')
              ru_content=$(echo $ru_content | sed "s/'/\\'/g")
              ru_content=$(echo $ru_content | sed 's/\n/\\n/g')
              ru_content=$(echo $ru_content | sed 's/\r/\\r/g')
              ru_content=$(echo $ru_content | sed 's/\t/\\t/g')
              ru_content=$(echo $ru_content | sed 's/\//\\//g')




              echo "email_content=$ru_content" >> $GITHUB_ENV
          env:
            MAILCHIMP_DC: ${{ secrets.MAILCHIMP_DC }}
            MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
            BASE_URL: https://roundup.stlgame.dev
            ISSUE_NO: 19

      -   name: update campaign
          run: |
                id=${{ env.campaign_id }}


                curl --location --request PUT "https://${{ env.MAILCHIMP_DC }}.api.mailchimp.com/3.0/campaigns/$id/content" \
                --header 'Content-Type: application/json' \
                --user "admin@stlgame.dev:${{ env.MAILCHIMP_API_KEY }}" \
                --data-raw '{
                  "html" : "${{ env.email_content }}"
                }'
          env:
            MAILCHIMP_DC: ${{ secrets.MAILCHIMP_DC }}
            MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}

      # -   name: test email
      #     run: |
      #       id=${{ env.campaign_id }}

      #       curl -X POST \
      #           "https://${{ env.MAILCHIMP_DC }}.api.mailchimp.com/3.0/campaigns/$id/actions/test" \
      #           --user "admin@stlgame.dev:${{ env.MAILCHIMP_API_KEY }}" \
      #           -d '{"test_emails":["tim@axolstudio.com"], "send_type":"html"}'
      #     env:
      #       MAILCHIMP_DC: ${{ secrets.MAILCHIMP_DC }}
      #       MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}